name: on_time

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
#   push:
#     branches:
#       - main
# schedule:
#   - cron: '0 0 * * *'
# 한국의 자정은 "0 15 * * *"이다

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
      - name: Generate Environment Variables File for Production
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL" >> .env
          echo "SUPABASE_API_KEY=$SUPABASE_API_KEY" >> .env
          echo "GIT_TOKEN=$GIT_TOKEN" >> .env
        env:
          REACT_APP_DOMAIN: ${{ secrets.REACT_APP_DOMAIN }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Run Crawler & Make Issue
        run: |
          python main.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
