name: on_time

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]
#   push:
#     branches:
#       - main
  # schedule:
  #   - cron: '0 0 * * *'
  # 한국의 자정은 "0 15 * * *"이다


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    
    - name: Install requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Crawler & Make Issue
      run: |
        python main.py
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
